import traceback
from typing import Annotated, Sequence, TypedDict
from langchain_core.messages import BaseMessage, AIMessage, ToolCall, ToolMessage, SystemMessage # The foundational class for all message types in LangGraph
from langchain_core.tools import tool
from langchain_groq import ChatGroq
from langgraph import graph
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from pydantic import BaseModel, Field
from tool import get_tools
from state import AgentState
from dotenv import load_dotenv

load_dotenv()



def get_model(have_tools: bool = True) -> ChatGroq:
    """
    Initializes and returns the LLM model with tools bound.

    This function sets up the ChatGroq model with the appropriate API key
    and binds the document retriever tool to it for use in the workflow.

    Args:
        have_tools (bool): A flag indicating whether to bind tools to the model. Defaults to True.
        
    Returns:
        An instance of the LLM model with tools bound for invocation in the workflow
    """
    
    llm = ChatGroq(model="openai/gpt-oss-120b", temperature=0.7)
    tools = get_tools()
    llm_with_tools = llm.bind_tools(tools) if have_tools else llm
    return llm_with_tools
    
    
def model_call(state:AgentState) -> AgentState:
    """
    Invokes the LLM model with the current conversation state and returns the updated state.

    Args:
        state (AgentState): The current state of the conversation, which includes the list of messages exchanged so far.
        
    Returns:
        AgentState: The updated state of the conversation, which includes the new message generated by the LLM model in response to the current conversation state.
    """
    
    model = get_model(have_tools=True)
    
    system_prompt = SystemMessage(content=
        "You are my AI assistant, please answer my query to the best of your ability."
    )
    #dòng trên tương đương {"role": "system", "content": "..."}
    response = model.invoke([system_prompt] + state["messages"])
    return {"messages": [response]} #returns the part being updated


def should_continue(state: AgentState) -> AgentState:
    """
    Determines whether the workflow should continue to the tool node or end based on the last message in the conversation state.
    
    Args:
        state (AgentState): The current state of the conversation, which includes the list of messages exchanged so far.
    Returns:
        str: A string indicating whether to continue to the tool node ("continue") or end the workflow ("end"). The decision is based on whether the last message in the conversation state contains any tool calls. If there are tool calls, it returns "continue"; otherwise, it returns "end".
    """
    
    messages = state["messages"]
    last_message = messages[-1]
    if not last_message.tool_calls: #kiểm tra xem có tín hiệu gọi tools từ message cuối cùng không
        return "end"
    else:
        return "continue"
    

def build_graph():
    """
    Builds and compiles the state graph for the ReAct agent workflow.
    """
    
    graph = StateGraph(AgentState)
    graph.add_node("our_agent", model_call)


    tool_node = ToolNode(tools=get_tools())
    graph.add_node("tools", tool_node)

    graph.set_entry_point("our_agent")

    graph.add_conditional_edges(
        "our_agent",
        should_continue,
        {
            "continue": "tools",
            "end": END,
        },
    )

    graph.add_edge("tools", "our_agent")

    app = graph.compile()
    
    return app


def run_chat():
    """
    Runs a simple command-line chat interface that interacts with the compiled state graph workflow.
    """
    
    app = build_graph()
    
    state = {"messages": []}


    while True:
        user_input = input("User: ")
        if user_input.lower() in ["exit", "quit", "q"]:
            break


        state["messages"].append(("user", user_input))

    
        config = {"configurable": {"thread_id": "1"}}
        
        try:
            output = app.invoke(state, config=config)
            
            state = output

            final_message = output["messages"][-1]
            print(f"AI: {final_message.content}")
            
        except Exception as e:
            print(f"Exception: {e}")
            traceback.print_exc()

if __name__ == "__main__":
    run_chat()



